projects:
  bookm:
    schemaPath: amplify/backend/api/bookm/build/schema.graphql
    includes:
      - app/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/services/api/graphql.ts
        docsFilePath: app/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
